spring:

  datasource:
    url: jdbc:h2:mem:customers_backend_test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true


security:
  aes:
    key: 12345abc12345abc
  token:
    key: 12345bbc
    duration: 43200000