file:
  upload-dir: /home/runner/work/UploadDir

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/customers_backend
    username: root
    password: XF*49b^qX&Tt6k

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

security:
  aes:
    key: fPW8SXtGcWG4vhCV
  token:
    key: MkrdPAJMBoeRPZX5BStzmJDJgmie69BzH4597BvKYr
    duration: 43200000
