spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mariadb://localhost:3306/customers_backend_test
    username: root
    password: admin

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true


security:
  aes:
    key: 12345abc12345abc
  token:
    key: 12345bbc
    duration: 43200000