spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/customers_backend
    username: root
    password: admin

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true

security:
  aes:
    key: 12345abc12345abc
  token:
    key: 12345bbc
    duration: 43200000