name: CI / CD with Github Actions

on:
  push:
    branches:  
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Hub Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true    
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Built Customers Backend Image
      working-directory: .
      run: docker compose build

    - name: Pushing to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/customers-backend:latest ${{ secrets.DOCKER_PASSWORD }}/customers-backend:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/customers-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/customers-backend:${{ github.run_id }}
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
