name: CI / CD with Github Actions

on:
  push:
    branches:  
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Hub Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true    
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Built Customers Backend Image App
      run: |
        pwd
        docker compose build
        
        
    - name: Pushing to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/customers-backend-final:latest
